# Generated by Django 3.0.5 on 2020-09-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('seller_company', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('seller_phone', models.CharField(max_length=150)),
                ('seller_type', models.CharField(max_length=150)),
                ('seller_mobile', models.CharField(max_length=150)),
                ('seller_fax', models.CharField(max_length=150)),
                ('others', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('billing_address', models.TextField()),
                ('terms', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
