# Generated by Django 3.0.5 on 2020-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=150)),
                ('customer_type', models.CharField(max_length=150)),
                ('customer_mobile', models.CharField(max_length=150)),
                ('customer_fax', models.CharField(max_length=150)),
                ('others', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('payment_method', models.CharField(max_length=150)),
                ('delivery_method', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=150)),
            ],
        ),
    ]
