# Generated by Django 3.0.5 on 2020-09-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='delivery_method',
        ),
    ]
