# Generated by Django 3.0.5 on 2020-09-14 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customer_delivery_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=150)),
                ('currency_symbol', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_company_id', models.BigIntegerField()),
                ('transport_company_name', models.CharField(max_length=150)),
                ('transport_company_address', models.TextField()),
                ('transport_company_city', models.CharField(max_length=150)),
                ('transport_company_country', models.CharField(max_length=150)),
                ('transport_company_postal_code', models.CharField(max_length=150)),
                ('pdf_attachment_box', models.FileField(blank=True, upload_to='Files')),
                ('notes', models.CharField(max_length=150)),
                ('transport_company_account_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='app.Currency')),
            ],
        ),
    ]
