# Generated by Django 3.0.5 on 2020-09-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_currency_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='lahore', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='Pakistan', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='app.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='pdf_attachment_box',
            field=models.FileField(blank=True, upload_to='Files'),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(default='54000', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(default='Lahore', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='country',
            field=models.CharField(default='Pakistan', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='app.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='pdf_attachment_box',
            field=models.FileField(blank=True, upload_to='Files'),
        ),
        migrations.AddField(
            model_name='seller',
            name='postal_code',
            field=models.CharField(default='54000', max_length=150),
            preserve_default=False,
        ),
    ]
