# Generated by Django 3.0.5 on 2020-09-16 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200915_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.BigIntegerField()),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('pdf_attachment_box', models.FileField(blank=True, upload_to='Files')),
                ('notes', models.CharField(max_length=150)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='app.Currency')),
            ],
        ),
    ]
