# Generated by Django 3.0.5 on 2020-09-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account_id', models.BigIntegerField()),
                ('bank_account_name', models.CharField(max_length=150)),
                ('bank_account_address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('pdf_attachment_box', models.FileField(blank=True, upload_to='Files')),
                ('notes', models.CharField(max_length=150)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='app.Currency')),
            ],
        ),
    ]
