# Generated by Django 3.0.5 on 2020-09-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_receipt_no', models.BigIntegerField()),
                ('transaction_type', models.CharField(max_length=150)),
                ('material', models.CharField(max_length=150)),
                ('purchase_quantity', models.IntegerField()),
                ('purchase_price', models.FloatField()),
                ('freight_cost', models.FloatField()),
                ('container_no', models.IntegerField()),
                ('pdf_attachment_box', models.FileField(blank=True, upload_to='Files')),
                ('notes', models.CharField(max_length=150)),
                ('exchange_rate', models.FloatField()),
                ('freight_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_freight_company', to='app.Transport')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_seller', to='app.Customer')),
                ('seller_account_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_seller_currency', to='app.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_invoice_no', models.BigIntegerField()),
                ('order_date', models.DateField()),
                ('material', models.CharField(max_length=150)),
                ('selling_quantity', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('date_of_arrival', models.DateField()),
                ('advance', models.FloatField()),
                ('payment_due_date', models.DateField()),
                ('pdf_attachment_box', models.FileField(blank=True, upload_to='Files')),
                ('exchange_rate', models.FloatField()),
                ('bank_account_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_payment_sale_order', to='app.BankAccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_currency', to='app.Currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order', to='app.Customer')),
                ('customer_account_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_customer_currency', to='app.Currency')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_purchase_order', to='app.PurchaseOrder')),
            ],
        ),
    ]
