# Generated by Django 3.0.5 on 2020-09-23 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_purchaseorder_saleorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='advance',
            field=models.FloatField(default=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bank_account_payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_payment_purchase_order', to='app.BankAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_currency', to='app.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
