# Generated by Django 3.0.5 on 2020-09-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200923_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_seller', to='app.seller'),
        ),
    ]
