# Generated by Django 3.0.5 on 2020-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200923_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='abbreviation',
            field=models.CharField(default='USD', max_length=150),
            preserve_default=False,
        ),
    ]
