# Generated by Django 3.0.5 on 2020-09-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_currency_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(max_length=300)),
                ('expense_type', models.CharField(max_length=150)),
                ('expense_date', models.DateField()),
                ('selling_quantity', models.IntegerField()),
                ('selling_price', models.FloatField()),
                ('pdf_attachment_box', models.FileField(blank=True, upload_to='Files')),
                ('notes', models.CharField(max_length=150)),
            ],
        ),
    ]
