# Generated by Django 3.0.5 on 2020-09-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_expenseentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='material',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='purchase_order_receipt_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='expense_entry', to='app.PurchaseOrder'),
            preserve_default=False,
        ),
    ]
