# Generated by Django 3.0.5 on 2020-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200923_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='payment_method',
            field=models.CharField(default='Cash Transfer', max_length=150),
            preserve_default=False,
        ),
    ]
