# Generated by Django 3.0.5 on 2020-09-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_paymentreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='exchange_rate',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
    ]
