# Generated by Django 3.0.5 on 2020-09-26 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_saleorder_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
                ('pdf_attachment_box', models.FileField(blank=True, upload_to='Files')),
                ('notes', models.CharField(max_length=150)),
                ('bankaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_made_bank_account', to='app.BankAccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_made_currency', to='app.Currency')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_made_expense', to='app.ExpenseEntry')),
                ('purchase_order_receipt_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_receipt_no', to='app.PurchaseOrder')),
            ],
        ),
    ]
