# Generated by Django 3.0.5 on 2020-09-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_paymentmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
