# Generated by Django 3.0.5 on 2020-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_saleorder_gross_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='payment_remaining',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
