# Generated by Django 3.0.5 on 2020-10-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_saleorder_payment_remaining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='billing_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='location',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='others',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='website',
        ),
    ]
