# Generated by Django 3.0.5 on 2020-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20201023_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='notes',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='postal_code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_fax',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_mobile',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_phone',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
