# Generated by Django 3.0.5 on 2020-10-23 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20201023_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='country',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='notes',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='postal_code',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_fax',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_mobile',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_phone',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
