# Generated by Django 3.0.5 on 2020-10-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20201023_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_company_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_company_country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_company_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='transport',
            name='transport_company_postal_code',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
