# Generated by Django 3.0.5 on 2020-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20201024_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account_id',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='postal_code',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
