# Generated by Django 3.0.5 on 2020-10-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20201024_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='advance_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_advance_currency', to='app.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='material',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
