# Generated by Django 3.0.5 on 2020-10-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20201027_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='unit',
            field=models.CharField(default='kgs', max_length=150),
            preserve_default=False,
        ),
    ]
