# Generated by Django 3.0.5 on 2020-10-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20201027_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='material',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
