# Generated by Django 3.0.5 on 2020-10-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20201027_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmade',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
