# Generated by Django 3.0.5 on 2020-10-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20201027_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceived',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='material',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
