# Generated by Django 3.0.5 on 2020-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20201001_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmade',
            name='expense',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_remaining',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
