# Generated by Django 3.0.5 on 2020-10-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20201001_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmade',
            name='exchange_rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmade',
            name='payment_remaining',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
