# Generated by Django 3.0.5 on 2020-10-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20201001_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='currency',
            new_name='seller_currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='seller_account_currency',
        ),
    ]
