# Generated by Django 3.0.5 on 2020-10-28 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20201027_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseentry',
            old_name='purchase_price',
            new_name='expense_cost',
        ),
        migrations.RenameField(
            model_name='expenseentry',
            old_name='purchase_quantity',
            new_name='expense_quantity',
        ),
        migrations.RemoveField(
            model_name='expenseentry',
            name='purchase_order_receipt_no',
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='bankaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account_expense', to='app.BankAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_currency', to='app.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='material',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='notes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
