# Generated by Django 3.0.5 on 2020-10-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20201028_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseentry',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenseentry',
            name='payment_remaining',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
