# Generated by Django 3.0.5 on 2020-10-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20201028_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=150)),
                ('expense_date', models.DateField()),
                ('material', models.CharField(blank=True, max_length=150)),
                ('amount', models.FloatField()),
                ('payment_remaining', models.FloatField()),
                ('pdf_attachment_box', models.FileField(blank=True, upload_to='Files')),
                ('notes', models.CharField(blank=True, max_length=150)),
                ('bankaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_bank_account_expense', to='app.BankAccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_expense_currency', to='app.Currency')),
                ('expense_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_id_new_expense', to='app.ExpenseEntry')),
            ],
        ),
    ]
