# Generated by Django 3.0.5 on 2020-12-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_newexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='disply_name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
