# Generated by Django 3.0.5 on 2020-12-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_purchaseorder_disply_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='disply_name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='saleorder',
            name='display_name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
