# Generated by Django 3.0.5 on 2020-12-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20201201_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='admin_cost',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleorder',
            name='unit',
            field=models.CharField(default='Kgs', max_length=150),
            preserve_default=False,
        ),
    ]
