# Generated by Django 3.0.5 on 2020-11-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_exchangerates'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='newexpense',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentmade',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymentreceived',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
