# Generated by Django 3.0.5 on 2020-11-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20201106_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerates',
            name='record_date',
        ),
    ]
