# Generated by Django 3.0.5 on 2020-11-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_remove_exchangerates_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank_account_title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
