# Generated by Django 3.0.5 on 2020-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20201110_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account_iban',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_account_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='opening_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
