# Generated by Django 3.0.5 on 2020-11-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20201111_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='net_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
