# Generated by Django 3.0.5 on 2020-11-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_bankaccount_net_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='amount_received',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='banking_charges',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleorder',
            name='amount_received',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleorder',
            name='banking_charges',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
