from django.urls import path
# current directory
from . import views
from django.conf.urls import url



urlpatterns = [
    url(r'^login/', views.login, name="login"),
    url(r'^add_seller/', views.add_seller, name="add_seller"),
    url(r'^view_seller/', views.view_seller, name="view_seller"),
    path(r'^<id>/view_seller/', views.individual_seller, name="individual_seller"),
    path(r'^<id>/delete_seller/', views.delete_seller, name="delete_seller"),
    path(r'^<id>/delete_customer/', views.delete_customer, name="delete_customer"),
    path(r'^<id>/delete_transport/', views.delete_transport, name="delete_transport"),
    url(r'^add_customer/', views.add_customer, name="add_customer"),
    path(r'^<id>/view_customer/', views.individual_customer, name="individual_customer"),
    path(r'^<id>/view_transport/', views.individual_transport, name="individual_transport"),
    path(r'^<id>/edit_transport/', views.edit_transport, name="edit_transport"),
    path(r'^<id>/edit_seller/', views.edit_seller, name="edit_seller"),
    path(r'^<id>/edit_customer/', views.edit_customer, name="edit_customer"),
    url(r'^view_customer/', views.view_customer, name="view_customer"),
    url(r'^add_transport/', views.add_transport, name="add_transport"),
    url(r'^view_transport/', views.view_transport, name="view_transport"),
    path(r'^<id>/view_employees/', views.individual_employee, name="individual_employee"),
    path(r'^<id>/delete_employee/', views.delete_employee, name="delete_employee"),
    path(r'^<id>/edit_employee/', views.edit_employee, name="edit_employee"),
    url(r'^view_employees/', views.view_employees, name="view_employees"),
    url(r'^add_employee/', views.add_employee, name="add_employee"),
    url(r'^add_currency/', views.add_currency, name="add_currency"),
    url(r'^add_bank/', views.add_bank, name="add_bank"),
    url(r'^view_bank/', views.view_bank, name="view_bank"),
    path(r'^<id>/edit_bank/', views.edit_bank, name="edit_bank"),
    path(r'^<id>/view_bank/', views.individual_bank, name="individual_bank"),
    path(r'^<id>/delete_bank/', views.delete_bank, name="delete_bank"),
    url(r'^sale_order/', views.sale_order, name="sale_order"),
    url(r'^expense_entry/', views.expense_entry, name="expense_entry"),
    url(r'^payment_received_entry/', views.payment_received_entry, name="payment_received_entry"),
    url(r'^payment_made_entry/', views.payment_made_entry, name="payment_made_entry"),
    url(r'^new_expense/', views.new_expense, name="new_expense"),
    url(r'^payment_made_ledger/', views.payment_made_ledger, name="payment_made_ledger"),
    url(r'^payment_received_ledger/', views.payment_received_ledger, name="payment_received_ledger"),
    url(r'^expense_made_ledger/', views.expense_made_ledger, name="expense_made_ledger"),
    path(r'^<id>/order_view/', views.order_view, name="order_view"),
    path(r'^<id>/purchase_order_view/', views.purchase_order_view, name="purchase_order_view"),
    path(r'^<id>/delete_payment_received/', views.delete_payment_received, name="delete_payment_received"),
    path(r'^<id>/delete_payment_made/', views.delete_payment_made, name="delete_payment_made"),
    path(r'^<id>/edit_payment_made_ledger/', views.edit_payment_made_ledger, name="edit_payment_made_ledger"),
    path(r'^<id>/edit_payment_received_ledger/', views.edit_payment_received_ledger, name="edit_payment_received_ledger"),
    path(r'^<id>/edit_expense_made_ledger/', views.edit_expense_made_ledger, name="edit_expense_made_ledger"),
    path(r'^<id>/delete_new_expense/', views.delete_new_expense, name="delete_new_expense"),
    path(r'^<id>/delete_purchase_order/', views.delete_purchase_order, name="delete_purchase_order"),
    path(r'^<id>/delete_sale_order/', views.delete_sale_order, name="delete_sale_order"),
    path(r'^<id>/export_to_csv/', views.export_to_csv, name="export_to_csv"),
    path(r'^<id>/customer_sale_orders/', views.customer_sale_orders, name="customer_sale_orders"),
    path(r'^<id>/seller_purchase_orders/', views.seller_purchase_orders, name="seller_purchase_orders"),
    path(r'^<id>/transport_purchase_orders/', views.transport_purchase_orders, name="transport_purchase_orders"),
    path(r'^<id>/bank_transactions/', views.bank_transactions, name="bank_transactions"),
    path(r'^<id>/print_purchase_order/', views.print_purchase_order, name="print_purchase_order"),
    path(r'^<id>/delete_expense_entry/', views.delete_expense_entry, name="delete_expense_entry"),
    path(r'^<id>/print_sale_order/', views.print_sale_order, name="print_sale_order"),
    path(r'^<id>/print_bank_invoice/', views.print_bank_invoice, name="print_bank_invoice"),
    url(r'^all_sale_orders/', views.all_sale_orders, name="all_sale_orders"),
    url(r'^all_purchase_orders/', views.all_purchase_orders, name="all_purchase_orders"),
    url(r'^get_next_sale_order/', views.get_next_sale_order, name="get_next_sale_order"),
    url(r'^get_order_invoice_no/', views.get_order_invoice_no, name="order_invoice_no"),
    url(r'^get_order_receipt_no/', views.get_order_receipt_no, name="order_receipt_no"),
    url(r'^all_expenses/', views.all_expenses, name="all_expenses"),
    url(r'^gross_profit_details/', views.gross_profit_details, name="gross_profit_details"),
    url(r'^get_purchase_order/', views.get_purchase_order, name="get_purchase_order"),
    url(r'^purchase_order/', views.purchase_order, name="purchase_order"),
    url(r'^logout/', views.logout, name="logout"),
    url(r'^$', views.index, name = 'index'),
    url(r'^expense_view/', views.expense_view, name="expense_view"),

]
handler404 = views.handler404
